### ISSUE TITLE
No module named 'adi._adi_cffi' error

### ISSUE THREAD

**Issue by rajan9** [JimHokanson/adinstruments_sdk_python#5]
I successfully installed using "pip install adi-reader" but when I ran the code it pop up error No module named 'adi._adi_cffi'

import adi
  File "C:\Users\lab\anaconda3\lib\site-packages\adi\__init__.py", line 3, in <module>
    from .read import read_file
  File "C:\Users\lab\anaconda3\lib\site-packages\adi\read.py", line 10, in <module>
    from adi._adi_cffi import ffi, lib
ModuleNotFoundError: No module named 'adi._adi_cffi'
[Finished in 0.586s]

**Comment by JimHokanson** [comment]
What version of Python are you using?

**Comment by rajan9** [comment]
I am using Python 3.8.8 :: Anaconda, Inc. on win32


Kind regards,
Rajan Shrivastava

**Comment by JimHokanson** [comment]
The problem is win32. I added the win32 drivers and updated the code. I'm waiting on someone to help with updating pypi. In the mean time you are welcome to clone/download this repo to test.

**Comment by rajan9** [comment]
Thanks a lot for the update. I am trying to test the code in my Windows 10
computer.
I uninstalled the earlier version of adi-reader which was installed using
pip. Next I downloaded the latest version of your code from
https://github.com/JimHokanson/adinstruments_sdk_python as a "download zip"
file and extracted the code in my anaconda working directory. I have placed
"adi folder" and "testcode.py" in the same location and running it.

Again it popup an error

from adi._adi_cffi2 import ffi, lib
ImportError: DLL load failed while importing _adi_cffi2: The specified
module could not be found.


probably I am doing something wrong?

Kind regards,
Rajan Shrivastava
Senior Research Fellow
Department of Biophysics
University of Delhi, South Campus
New Delhi - 110021
URL: https://sites.google.com/view/profsubhendughosh/home

**Comment by JimHokanson** [comment]
hmm, can you confirm you have numpy installed? Also, the code should be updated on pypi now. Is that the full error? I tested it on my end and it worked ...

**Comment by rajan9** [comment]
Yes numpy is installed as I have anaconda installed on my computer. Now I
have reinstalled the script using pypi but still shows error in my system

*Your test code*
import matplotlib.pyplot as plt
*import numpy*
import adi
f = adi.read_file(r'C:\Users\RNEL\Desktop\test\test_file.adicht')
# All id numbering is 1 based, first channel, first block
# When indexing in Python we need to shift by 1 for 0 based indexing
# Functions however respect the 1 based notation ...

# These may vary for your file ...
channel_id = 2
record_id = 1
data = f.channels[channel_id-1].get_data(record_id)
plt.plot(data)
plt.show()

*output*

Traceback (most recent call last):
  File "C:\Users\read_adicht.py", line 3, in <module>

    import adi
  File "C:\Users\adi\__init__.py", line 3, in <module>
    from .read import read_file
  File "C:\Users\adi\read.py", line 14, in <module>
    from adi._adi_cffi2 import ffi, lib
ImportError: DLL load failed while importing _adi_cffi2: The specified
module could not be found.

[Finished in 0.757s]



Kind regards,
Rajan Shrivastava

**Comment by JimHokanson** [comment]
Hmm, I have no idea at this point why it is not working. I tried running this:

https://github.com/lucasg/Dependencies

running the DependenciesGui.exe and everything resolved fine (except Python, but that's expected). Can you confirm you are using 3.8 and not another version of Python?

You're more than welcome to look at the DependenciesGui.exe to see if anything is strange on your end. Otherwise I have no idea. At this point everything should work .... I'm open to suggestions.
